eureka:
  client:
    enabled: false
    registerWithEureka: false
  fetchRegistry: false

# Server configuration
server:
  port: ${SERVICE_PORT:8082}
  servlet:
    context-path: /micro

management:
  server:
    port: ${MANAGEMENT_PORT:8092}

# Spring properties
spring:
  application:
    name: customer
    cloudant:
      protocol: http #//${COUCHDB_PROTOCOL:http}
      username: admin #${COUCHDB_USER:admin}
      password: passw0rd #${COUCHDB_PASSWORD:passw0rd}
      host: 127.0.0.1 #${COUCHDB_HOST:127.0.0.1}
      port: 5985 #${COUCHDB_PORT:5985}
      database: customers #${COUCHDB_DATABASE:customers}

jwt:
  sharedSecret: ${HS256_KEY:}